# Generated by Django 3.2.16 on 2022-12-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songmodel',
            name='thumbnail_url',
            field=models.CharField(blank=True, default=None, max_length=1024, null=True),
        ),
    ]
