# Generated by Django 3.2.16 on 2022-12-07 17:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_songmodel_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songmodel',
            name='uid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
