# Generated by Django 3.2.16 on 2022-12-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_songmodel_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='songmodel',
            name='length',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
