# Generated by Django 3.2.16 on 2022-12-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_songmodel_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='songmodel',
            name='uid',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
    ]
