# Generated by Django 3.2.16 on 2022-12-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_songmodel_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='songmodel',
            name='song_path',
            field=models.CharField(blank=True, default=None, max_length=1024, null=True),
        ),
    ]
